title: Xblog
subtitle: "A powerful and fast blog system powered by laravel 5.3."
description: "Xblog is a powerful, simple & fast blog framework powered by laravel 5.3."
author: lufficc
language: zh-cn
timezone: UTC
url: https://lufficc.github.io/Xblog
root: /Xblog
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

theme: navy
deploy:
  type: git
  repo: https://github.com/lufficc/Xblog.git
  branch: gh-pages

disqus_shortname: laravel-blog
google_analytics: UA-4910098-10
fb_admins: 100000247608790

github: lufficc/Xblog
